'use strict'

/** @type {Business[]} */
export const businesses = [
  { 'id': 'bus-01', 'nickname': 'Software Consulting, LLC' },
  { 'id': 'bus-02', 'nickname': 'Hair Salon, LLC' }]

/** @type {FinancialAccount[]} */
export const accounts = [
  {
    'id': 'acc-01',
    'tenantId': 'tenant-01',
    'shortName': 'Checking Main',
    'fullName': 'BoA Personal Checking',
    'type': 'checking',
    'bankId': 'bank-01',
    'closed': 0,
    'visible': 1,
    'deleted': 0,
    'businessId': null,
    'isDefault': 1,
    'openingBalance': 0,
    format: null,
    'balance': 0
  },
  {
    'id': 'acc-02',
    'tenantId': 'tenant-01',
    'shortName': 'Amazon CC',
    'fullName': 'Chase Amazon CC',
    'type': 'CC',
    'bankId': 'bank-02',
    'closed': 0,
    'visible': 1,
    'deleted': 0,
    'businessId': null,
    'isDefault': null,
    'openingBalance': 0,
    format: null,
    'balance': 0
  },
  {
    'id': 'acc-03',
    'shortName': 'Citi MasterCard',
    'tenantId': 'tenant-01',
    'fullName': 'Citi Mastercard Main',
    'type': 'CC',
    'bankId': 'bank-03',
    'closed': 0,
    'visible': 1,
    'deleted': 0,
    'businessId': null,
    'isDefault': null,
    'openingBalance': 0,
    format: 'citiCard',
    'balance': 0
  },
  {
    'id': 'acc-04',
    'tenantId': 'tenant-01',
    'shortName': 'CapitalOne Visa',
    'fullName': 'CapitalOne Visa',
    'type': 'CC',
    'bankId': 'bank-03',
    'closed': 0,
    'visible': 1,
    'deleted': 0,
    'businessId': null,
    'isDefault': null,
    'openingBalance': -612143,
    format: 'citiCard',
    'balance': 0
  },
  {
    'id': 'acc-05',
    'tenantId': 'tenant-01',
    'shortName': 'BoA Business',
    'fullName': 'BoA Consulting Business',
    'type': 'checking',
    'bankId': null,
    'closed': 0,
    'visible': 1,
    'deleted': 0,
    'businessId': 'bus-01',
    'isDefault': null,
    'openingBalance': 0,
    format: null,
    'balance': 50000
  },
  {
    'id': 'acc-06',
    'tenantId': 'tenant-01',
    'shortName': 'Salon Checking',
    'fullName': 'WellsFargo Salon Business Checking',
    'type': 'checking',
    'bankId': 'bank-02',
    'closed': 0,
    'visible': 1,
    'deleted': 0,
    'businessId': 'bus-02',
    'isDefault': null,
    'openingBalance': 0,
    format: null,
    'balance': 1430784
  }]

export const amazonAccount = accounts[1]
export const citiAccount = accounts[2]

/** @type {psbf.Category[]} */
export const categories = [
  { 'id': 'cat-101', 'name': 'CC payment', 'isPersonal': 1, 'type': 't' },
  { 'id': 'cat-100', 'name': 'Transfer', 'isPersonal': 1, 'type': 't' },
  { 'id': 'cat-102', 'name': 'Transfer', 'isPersonal': 1, 'type': 't' },
  { 'id': 'cat-103', 'name': 'Income', 'isPersonal': 1, 'type': 'i' },
  { 'id': 'cat-104', 'name': 'Interest Income', 'isPersonal': 1, 'type': 'i' },
  { 'id': 'cat-105', 'name': 'Paycheck', 'isPersonal': 1, 'type': 'i' },
  { 'id': 'cat-106', 'name': 'Tax Rebate', 'isPersonal': 1, 'type': 'i' },
  { 'id': 'cat-107', 'name': 'Unemployment Income', 'isPersonal': 1, 'type': 'i' },
  { 'id': 'cat-108', 'name': 'Food misc', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-109', 'name': 'Auto Insurance', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-110', 'name': 'Auto payment', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-111', 'name': 'Bank Fee', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-112', 'name': 'Car', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-113', 'name': 'Charity', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-114', 'name': 'Check', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-02', 'name': 'Entertainment', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-115', 'name': 'Federal Tax', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-116', 'name': 'Food', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-117', 'name': 'Gas & Fuel', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-118', 'name': 'Gifts', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-119', 'name': 'Health', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-120', 'name': 'Home', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-121', 'name': 'Home Insurance', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-122', 'name': 'Life Insurance', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-1221', 'name': 'Loan', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-123', 'name': 'Misc Expenses', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-124', 'name': 'Mortgage & Rent', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-125', 'name': 'Personal Care', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-126', 'name': 'Pet Insurance', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-127', 'name': 'Pets', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-128', 'name': 'Phone', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-129', 'name': 'Property Tax', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-01', 'name': 'Shopping', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-130', 'name': 'State Tax', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-03', 'name': 'Utilities', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-131', 'name': 'Vacation', 'isPersonal': 1, 'type': 'e' },
  { 'id': 'cat-1311', 'name': 'Business Income', 'isPersonal': 0, 'type': 'i' },
  { 'id': 'cat-132', 'name': 'Advertising', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-133', 'name': 'Business Travel', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-134', 'name': 'Car - parking & tolls', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-135', 'name': 'Commissions', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-136', 'name': 'Communication', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-137', 'name': 'Contract Labor', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-138', 'name': 'Health Insurance', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-139', 'name': 'Insurance Payment', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-140', 'name': 'Interest Payment', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-141', 'name': 'Legal and Professional Fees', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-142', 'name': 'Loan', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-143', 'name': 'Meals', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-144', 'name': 'Moving', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-145', 'name': 'Office Expenses', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-146', 'name': 'Other Misc Expenses', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-147', 'name': 'Rental Expenses', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-148', 'name': 'Repair and Maintenance', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-04', 'name': 'Supplies', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-149', 'name': 'Taxes and Licences', 'isPersonal': 0, 'type': 'e' },
  { 'id': 'cat-150', 'name': 'Utilities', 'isPersonal': 0, 'type': 'e' }]

/** @type {Car[]} */
export const cars = [{ 'id': 'car-01', 'description': 'Ford F-150', 'isInUse': 1 }]

/** @type {psbf.Transaction[]} */
export const transactions = [
  {
    'id': 'trans-001',
    'postedDate': '2021-02-28T06:00:00.000Z',
    'accountId': 'acc-02',
    'categoryId': 'cat-01',
    'amount': -18.39,
    'businessId': 'p',
    'description': 'Amazon',
    'originalDescription': 'Amazon',
    'sourceOriginalDescription': 'Amazon.com*UO8PC37777',
    'reconciled': 1,
    'deleted': 0,
    'source': 'i',
    'scheduled': 1,
    'parentId': null,
    'hasChildren': 0,
    'tripId': null,
    'note': 'Test note 1'
  },
  {
    'id': 'trans-002',
    'postedDate': '2021-02-28T06:00:00.000Z',
    'accountId': 'acc-02',
    'categoryId': 'cat-02',
    'amount': -2.99,
    'businessId': 'p',
    'description': 'Apple',
    'originalDescription': 'Apple',
    'sourceOriginalDescription': 'APPLE.COM/BILL',
    'reconciled': 1,
    'deleted': 0,
    'source': 'i',
    'scheduled': 1,
    'parentId': null,
    'hasChildren': 0,
    'tripId': null,
    'note': ''
  },
  {
    'id': 'trans-003',
    'postedDate': '2021-02-28T06:00:00.000Z',
    'accountId': 'acc-02',
    'categoryId': 'cat-03',
    'amount': -106.95,
    'businessId': 'p',
    'description': 'PG&E',
    'originalDescription': 'PG&E ENERGY SERVICES',
    'sourceOriginalDescription': 'PG&E ENERGY SERVICES',
    'reconciled': 1,
    'deleted': 0,
    'source': 'i',
    'scheduled': 1,
    'parentId': null,
    'hasChildren': 0,
    'tripId': null,
    'note': ''
  },
  {
    'id': 'trans-004',
    'postedDate': '2021-02-22T06:00:00.000Z',
    'accountId': 'acc-03',
    'categoryId': 'cat-04',
    'amount': -107.91,
    'businessId': 'bus-02',
    'description': 'Rda Pro Mart',
    'originalDescription': 'Rda Pro Mart',
    'sourceOriginalDescription': 'RDA PRO MART-DUBLIN CA',
    'reconciled': 1,
    'deleted': 0,
    'source': 'i',
    'scheduled': 1,
    'parentId': null,
    'hasChildren': 0,
    'tripId': 'trip-001',
    'note': ''
  },
  {
    'id': 'trans-005',
    'postedDate': '2021-02-20T06:00:00.000Z',
    'accountId': 'acc-03',
    'categoryId': 'cat-01',
    'amount': -24.67,
    'businessId': 'p',
    'description': 'White House/Black Market',
    'originalDescription': 'White House/Black Market',
    'sourceOriginalDescription': 'WhiteHouseBlackMarket 888-851-4986 FL',
    'reconciled': 1,
    'deleted': 0,
    'source': 'i',
    'scheduled': 1,
    'parentId': null,
    'hasChildren': 0,
    'tripId': null,
    'note': ''
  }
]

export const amazonCardTransactions = transactions.filter(x => x.accountId === amazonAccount.id)
export const citiCardTransactions = transactions.filter(x => x.accountId === citiAccount.id)

